### ISSUE TITLE
Fix alignment - Quick start menu

### ISSUE THREAD

**Issue by ShrutiK100** [DACCS-Climate/marble-website#120]
Fix alignment for the Quick start menu and adjust opacity 

opacity: 0.4;
background: url(<path-to-image>) lightgray -126.294px 0px / 147.687% 121.823% no-repeat, rgba(0, 0, 0, 0.50);

/* Elevation 3 */
box-shadow: 0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.30);

Use layer with 50% opacity 
![Quickstart-layer](https://github.com/DACCS-Climate/marble-website/assets/161752175/73ccbec8-3548-4205-9c00-77956b341f6f)

@alexandercyu

**Comment by alexandercyu** [comment]
The quickstart already has Elevation 3.

Is the lightgray colour in the design system?
