### ISSUE TITLE
Close Button "X" position changed

### ISSUE THREAD

**Issue by ShrutiK100** [DACCS-Climate/marble-website#123]
Please note that close button position is changed since its position doesn't seem to be co-ordinating with the design inspire of correct values. The new position is same as the current position of Hamburger menu. 
Also note the hamburger menu and "X" button colour change to 500 - #9E9E9E(only for home screen)

So position of "X" is x=35, Y=60
hamburger menu with have the same portion  with medium size 40px x 40px
Close button small size 16px x 16px

**Comment by mishaschwartz** [comment]
resolved in #122
