### ISSUE TITLE
Marble website Nodes and About page - Banner misaligned

### ISSUE THREAD

**Issue by ShrutiK100** [DACCS-Climate/marble-website#157]
Both nodes and banner page misaligned, top tab navigator is not fixed in its position anymore-scrolls with the banner, similar misalignments can be seen in the mobile design as well.
<img width="1512" alt="Screenshot 2024-06-19 at 10 24 49 AM" src="https://github.com/DACCS-Climate/marble-website/assets/161752175/4b313f8a-4ad9-4f6d-abbd-fc03bb622fad">
<img width="1512" alt="Screenshot 2024-06-19 at 10 24 49 AM" src="https://github.com/DACCS-Climate/marble-website/assets/161752175/4b313f8a-4ad9-4f6d-abbd-fc03bb622fad">
<img width="1512" alt="Screenshot 2024-06-19 at 10 27 42 AM" src="https://github.com/DACCS-Climate/marble-website/assets/161752175/a3c39c7d-b9b4-4ffb-affa-cd71fd951102">
<img width="1512" alt="Screenshot 2024-06-19 at 10 27 42 AM" src="https://github.com/DACCS-Climate/marble-website/assets/161752175/a3c39c7d-b9b4-4ffb-affa-cd71fd951102">
@alexandercyu @mishaschwartz

**Comment by mishaschwartz** [comment]
@ShrutiK100 please restart your browser. This is due to your browser caching the css from before yesterday when the code was updated.
