### ISSUE TITLE
JupyterHub -> JupyterLab

### ISSUE THREAD

**Issue by huard** [DACCS-Climate/marble-website#161]
In the description of each node's software, JupyterHub is listed when it should be JupyterLab.

**Comment by alexandercyu** [comment]
Just to be sure, you're saying JupyterHub listed in the node's services should be JupyterLab?

![Screenshot 2024-09-16 at 1 20 41 PM (3)](https://github.com/user-attachments/assets/afc8645c-13d6-4b4c-ada5-f17b2b43ee7f)

**Comment by huard** [comment]
I checked again to make sure and realized I missed a nuance. 

My current understanding is that JupyterLab (what the users see) runs within JupyterHub (what the server runs), so both are valid. 

Which one you put there depends on who the page is intended for. My weak preference goes to JupyterLab, but I understand why you'd want to list JupyterHub instead.
