### ISSUE TITLE
Landing page: text of PAVICS logo blends in background

### ISSUE THREAD

**Issue by huard** [DACCS-Climate/marble-website#29]
![image](https://github.com/DACCS-Climate/marble-website/assets/81219/ec29e306-65bc-4a72-9a6b-54cda78080d4)

**Comment by alexandercyu** [comment]
Is it possible to provide the logo with no text in the node registry?

https://pavics.ouranos.ca/assets/images/pavics_no_text.svg

**Comment by huard** [comment]
Sure, or this one if you prefer. 

![pavics_h](https://github.com/DACCS-Climate/marble-website/assets/81219/aedd98d5-c9ad-4b0d-a81e-f80c4e5eff6c)

I have an SVG of this is you prefer.

**Comment by alexandercyu** [comment]
I think for the space available, the logo with no text will be better.
