### ISSUE TITLE
Update description of Raven

### ISSUE THREAD

**Issue by huard** [DACCS-Climate/marble-website#36]
Some functionalities of Raven have been removed a few months back, the description should reflect the current state. I'll submit a PR for this.

**Comment by alexandercyu** [comment]
The description was taken from the github page (https://github.com/bird-house/raven), which lists different technologies used.  The more up to date description is probably on ReadtheDocs (https://pavics-sdi.readthedocs.io/projects/raven/en/latest/)  but the description with the different listed technologies sounds more impressive.

**Comment by huard** [comment]
Closed by #41
