### ISSUE TITLE
About: add members and affiliations of executive committee

### ISSUE THREAD

**Issue by huard** [DACCS-Climate/marble-website#39]

**Comment by huard** [comment]
Like this: https://www.ouranos.ca/en/equipe#david-huard-408 ?

**Comment by alexandercyu** [comment]
Yes, that's perfect!  I'll put it on the site.

**Comment by mishaschwartz** [comment]
I guess I need to make a personal page... I'll put something together next week

**Comment by fmigneault** [comment]
Consider supporting multiple links per profile. 
In my case, CRIM does not have a single page per employee.
I would instead refer to my various public profiles: 

- https://orcid.org/0000-0003-4862-3349
- https://github.com/fmigneault/
- https://www.linkedin.com/in/francis-charette-migneault/

**Comment by mishaschwartz** [comment]
For now, please use https://github.com/mishaschwartz/ for me please
