### ISSUE TITLE
Document submodule cloning

### ISSUE THREAD

**Issue by dchandan** [DACCS-Climate/marble-website#42]
We should probably add to [Readme](https://github.com/DACCS-Climate/marble-website/blob/main/README.md) that after cloning the repo one should do the following to also clone the submodules:

    git submodule init
    git submodule update

**Comment by mishaschwartz** [comment]
In addition to this? 

https://github.com/DACCS-Climate/marble-website/blob/8139388/README.md?plain=1#L21-L25

**Comment by dchandan** [comment]
I think so. That didn't work for me. Typical instructions on submodules say that to complete the cloning process you have to execute those commands. I think (I might be wrong) the existing command comes in use when you are pulling changes from the central repo and you want to make sure you recursively pull the submodules too.
