### ISSUE TITLE
Add setNodeLink function for the datacatalog pages

### ISSUE THREAD

**Issue by mishaschwartz** [DACCS-Climate/marble-website#49]
PR #46 introduces the `setNodeLink` function for the ide.html page. We should also add the same functionality to the datacatalog.html page to navigate to the stac-browser endpoint

**Comment by alexandercyu** [comment]
What if they don't have a stac-browser endpoint?  Should it go to the thredds endpoint?

**Comment by mishaschwartz** [comment]
No, this page only contains content about STAC now.
I'd update the nodeFilter function on this page to filter out nodes that don't have a stac-browser endpoint instead

**Comment by alexandercyu** [comment]
Change made.  Only nodes with stac-browser will be shown.

**Comment by mishaschwartz** [comment]
> Change made. Only nodes with stac-browser will be shown.

where did you make this change?

**Comment by alexandercyu** [comment]
Should be in the datacatalog.html file.  I set it to only select "stac-browser" from the json.

**Comment by mishaschwartz** [comment]
I meant which PR? The change does not appear to have been added to master:

https://github.com/DACCS-Climate/marble-website/blob/main/templates/site/datacatalog.html#L26

**Comment by alexandercyu** [comment]
Sorry. Forgot to make it.

https://github.com/DACCS-Climate/marble-website/pull/56
